# Generated by Django 3.0.4 on 2020-03-17 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_item_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='prince',
            new_name='price',
        ),
    ]
