# Generated by Django 3.0.4 on 2020-03-17 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_item_discount_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='description',
            field=models.TextField(default='Descriptipon article'),
            preserve_default=False,
        ),
    ]
