# Generated by Django 3.0.4 on 2020-03-17 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20200317_1556'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='order',
            new_name='is_ordered',
        ),
    ]
