# Generated by Django 3.0.4 on 2020-03-22 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_order_billing_adress'),
    ]

    operations = [
        migrations.RenameField(
            model_name='billingadress',
            old_name='countries',
            new_name='country',
        ),
    ]
