# Generated by Django 3.0.4 on 2020-04-04 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_auto_20200329_1126'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BillingAdress',
        ),
    ]
